version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    ignore:
      # focus only on security patches - ignore major and minor version updates
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    # .NET SDK updates are mostly released on “patch Tuesday” (the second Tuesday of each month)
    schedule:
      interval: "weekly"
      day: "wednesday"
    ignore:
      # focus only on security patches - ignore major and minor version updates
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    ignore:
      # focus only on security patches - ignore major and minor version updates
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"